CREATE DATABASE spotFinderDB;

CREATE TABLE users(
    id INT(10) NOT NULL AUTO_GENERATE PRIMARY KEY,
    userName: VARCHAR(20) NOT NULL PRIMARY KEY,
    mail: string VARCHAR(30) NOT NULL PRIMARY KEY,
    password NOT NULL
)

DESCRIBE users